## Questão 1

Considere a matriz ```A``` apresentada abaixo:

Calcule os autovalores e autovetores da matriz e responda:

B - Qual o maior autovalor da matriz?


C - Qual o autovetor correspondente ao maior autovalor da matriz?


D - Qual o menor autovalor da matriz?


E - Qual o autovetor correspondente ao menor autovalor da matriz?

In [8]:
import numpy as np

A = np.array([[0.50, 0.16], [0.59, 0.32]])

w, v = np.linalg.eig(A)

# print("Auto Valores")
# print(w)
# print("Auto Vetores")
# print(v)

B = w.T[0]
C = v.T[0]
D = w.T[-1]
E = v.T[-1]


## Questão 2

Calcule os autovalores e autovetores da matriz e responda:

B - Qual o maior autovalor da matriz?

C - Qual o autovetor correspondente ao maior autovalor da matriz? (coloque os elementos na mesma linha)

In [11]:
import numpy as np
import numpy as np

A = np.array([[0.35, 0.76, 0.22, 0.86, 0.86, 0.77, 0.11, 0.22], [0.79, 0.08, 0.90, 0.65, 0.28, 0.47, 0.68, 0.12], [0.02, 0.19, 0.01, 0.26, 0.21, 0.16, 0.22, 0.37], [0.24, 0.68, 0.73, 0.68, 0.42, 0.26, 0.52, 0.21], [0.74, 0.69, 0.58, 0.70, 0.72, 0.14, 0.96, 0.62], [0.82, 0.73, 0.87, 0.20, 0.09, 0.46, 0.73, 0.34], [0.68, 0.81, 0.46, 0.64, 0.47, 0.70, 0.70, 0.42], [0.12, 0.08, 0.78, 0.32, 0.47, 0.80, 0.29, 0.79]])

w, v = np.linalg.eig(A)

# print("Auto Valores")
# print(w)
# print("Auto Vetores")
# print(v)

B = w.T[0]
C = v.T[0]
C

array([0.38306459, 0.33370737, 0.13377002, 0.31392688, 0.46810992,
       0.35391444, 0.43949664, 0.29650764])

## Questão 3

Considere os autovalores w e os autovetores v abaixo de modo que os valores na coluna v[:,i] são os autovetores correspondentes ao autovalor w[i].

B - Qual a matriz ```A``` cujos autovalores são w e os autovetores v? (Dica: utilize np.diag para converter uma lista de números em uma matriz diagonal)

In [13]:
import numpy as np


# Pense que este W e V são os resultados de um linalg.eig(A)
v = np.array([[0.59352948, 0.82700895, -0.56344498], [0.71518516, -0.21790266, -0.37484387], [0.36909746, -0.51824186, 0.73622132]])
w = np.array([1.25409524, -0.35622488, -0.05787036])

w_ = np.diag(w)
B = v @ w_ @ np.linalg.inv(v)
B

array([[0.12999999, 0.68000001, 0.48999999],
       [0.62999999, 0.37000001, 0.69999999],
       [0.46      , 0.09000001, 0.34      ]])

# Question 1: Autovalores e Autovetores: Exercício 6

In [4]:
import numpy as np

v = np.array([[-0.59134872, -0.35412393, 0.55580228, 0.19897486, -0.29497267,  -0.29897640], [-0.46118078, -0.26190737, -0.03502328, -0.55757088, 0.17554200,  0.61301706], [-0.51585599, 0.00582689, -0.63090737, 0.07151755, 0.34949818,  -0.45667362], [0.38074559, -0.88655777, -0.13230546, 0.06071938, 0.19439553,  -0.10033402], [-0.06748766, 0.08856088, 0.33318249, 0.51361796, 0.73765031, 0.26203134], [-0.14828954, -0.11017759, -0.40410120, 0.61393706, -0.42203027,  0.49753901]])
w = np.array([1.86920952, 0.33105336, 1.11226779, 0.96525378, 0.63486450, 0.73005467])

In [5]:
# Apresente uma matriz de duas colunas onde cada uma contém os autovetores que devem ser utilizados para projetar os dados em duas dimensões:
matriz = np.array([v.T[0], v.T[2]]).T
matriz

array([[-0.59134872,  0.55580228],
       [-0.46118078, -0.03502328],
       [-0.51585599, -0.63090737],
       [ 0.38074559, -0.13230546],
       [-0.06748766,  0.33318249],
       [-0.14828954, -0.4041012 ]])

# Question 2: Autovalores e Autovetores: Exercício 7

In [7]:
import numpy as np

dados = np.array([[1.91449170, -0.91682406, 0.49182844, 0.08078321, 0.04492966,  -0.60581401, 0.97888022, -0.61707896, 0.51715150, 0.38566725,  0.65845475, -1.73457727], [-0.55416204, -2.34278778, 1.50513062, -0.48903180, 0.08604193,  0.76480614, -0.00466416, -1.31290199, -0.43187957, -0.78911677,  1.19586666, 0.53910466], [0.94985504, -0.27551342, 1.00319523, 1.31246239, -0.88724694,  0.15435982, -0.14524614, -0.10848144, -0.33419948, -0.90613352,  -0.23878193, 0.79143484], [-1.05706452, 0.24596241, -0.48103323, 0.77285562, -0.76080827,  0.22926758, 0.08573649, -0.89058560, -1.23730158, -0.42092491,  1.75610891, 0.59473409], [0.11447608, 0.54674577, -0.40360693, 0.80397522, 1.65338672, 0.36151934,  -1.23649307, 0.09465076, 0.76394147, 0.37521043, 1.31794403, 1.32651403], [-1.04844103, -1.58133698, -0.43991339, 0.44969560, 0.92888206,  0.99309483, 0.96477371, -0.13804193, 0.76463957, -0.84703457,  0.50528535, -0.59068283], [1.07976236, 0.87803040, -1.47652668, -1.27625150, 0.45512450,  1.35018425, 0.64094840, -1.14334656, 0.85593825, -0.70957556,  0.29018718, 0.83147479], [1.67287392, -1.77484028, 0.68032483, -1.73106229, -0.36012751,  -0.20440693, 1.80826095, -0.48807812, 0.57738493, -0.54601628,  1.79166900, -0.95417552], [-0.70587378, -0.47261020, -0.55656527, -1.95826537, 0.15387528,  0.60183718, -0.86084572, 0.40438257, 0.15747871, -0.42045920,  0.82993225, -0.31761039], [-0.81289661, 0.47396814, 0.68842527, -0.46484211, 0.98723951,  -0.07365829, -0.49777228, -0.71221550, -1.06821065, -0.51191247,  -0.70804766, 0.18313514], [-0.18404283, -0.39484662, -0.39672040, -0.32436651, 0.72401186,  1.75508387, -0.41957579, 0.20919151, 2.34997547, 0.21359706, 0.23714366,  -0.06395687], [-1.88191778, 1.68889634, 1.29927776, -0.05587172, -2.19578331,  -0.86745787, 0.68410674, -0.68728314, -0.70454332, -1.54352993,  -0.21621565, -0.61070379], [1.16681401, -0.77772713, -0.18156202, 0.36314715, 0.13877694,  -0.44504544, 0.08322747, 0.15992071, 0.87709323, -0.63499806,  -0.42491374, 1.44237793], [0.39285296, -1.16163761, 0.69455335, 0.99132181, -0.22008118,  -0.34857355, -0.88126936, -1.16140650, 2.84278076, -0.18713268,  -0.90829448, 0.78748362], [-0.82637255, -0.38969448, -0.05888722, 1.08537911, 0.84163537,  0.22308371, 0.64056630, -1.60440557, -1.00054229, 2.26103409,  -1.11094755, -0.64937432], [-1.48769637, 0.30649699, -0.85758791, 1.00983567, -1.10302830,  0.82772839, 0.33958009, -0.05862736, -0.55087161, -0.87060312,  0.66413966, -0.52825104], [-0.79213556, -1.17051115, 1.29112355, -2.13646247, 1.00641775,  0.11992990, -0.11076214, 0.77434785, 1.03193229, 1.64171562, 0.80092646,  0.69163550], [-0.62925224, -1.82502751, -0.30810012, -0.56870612, -0.78502037,  0.10749828, 1.75329053, -1.26545318, -0.49789999, 0.77522573,  -0.51818063, 0.14650942], [0.97157056, -0.68377336, -0.09459764, 0.00836613, -0.58544179,  -0.41036892, -1.89479155, 1.74299853, 0.00413852, -0.79571759,  -2.59264131, -0.42730977], [-0.67091456, -2.36662069, -0.33172212, -0.50580061, -1.10654909,  -0.67719983, -0.54625103, 0.49580344, -0.24431399, -1.21936556,  -0.10297581, 1.22280495], [1.45504752, -0.24096598, 1.06102275, -0.99448155, -0.96818118,  -0.89590873, 0.93562164, -1.06237090, -0.81598378, -1.12919271,  0.51884070, -0.61686386], [0.57660952, -0.13563939, 0.54481637, -0.35467039, -0.72885639,  0.32306242, -1.12032239, 0.70890600, -0.57802170, 0.35259298,  -0.19289304, 1.03884855], [-0.76643362, -0.80175498, 0.57810602, -1.64523822, 0.18849274,  0.59805918, 1.90449535, 1.22213513, -3.60418712, 1.34391748,  -1.19216394, -0.19436004], [-1.38703174, 1.24983861, 2.15300030, -0.65506987, -0.81614922,  1.09324787, -1.11465275, 0.00377541, 1.31870702, 0.21761657, 0.68176028,  1.28382005], [0.17944340, 0.64382159, 0.36178568, -0.86974040, -0.65996840,  -1.20591649, 1.92571225, -1.62873841, -0.05816393, 0.79896491,  0.84996977, -0.28483159], [-1.41092735, 0.94809837, 1.24512913, -1.10903303, -2.09889478,  -0.48502632, -0.45305076, -0.25775147, 0.13882136, 0.03503406,  -1.47273993, 0.42193214], [-1.61071815, 0.64128150, -0.10566152, 1.06382746, 1.35171272,  -0.92446334, -1.22657443, -0.97994795, -0.15124707, 0.93545939,  -0.56484007, 1.35923189], [0.39338463, -0.86607840, 0.11898251, -0.90417879, -0.13700399,  0.74500350, -0.30007643, -0.79091909, -0.34076677, 0.50832919,  -0.10202624, -1.95103997], [-0.25525118, 0.98203451, 0.64112255, -0.57351080, 0.49160130,  0.25261068, 0.74808146, -0.88903949, -0.27230276, 0.37888298,  -0.59591178, -0.58579554], [0.69786212, -0.50630156, -0.33704566, 0.58952842, -0.12413034,  -0.76694248, -0.78370619, -1.74432546, 0.25122970, -1.50088358,  -0.61616593, -1.30731618]])

In [17]:
# Utilizando a Análise de Componentes Principais com duas componentes da biblioteca scikit-learn, apresente a matriz com os valores das componentes. Cada componente deve estar em uma coluna da matriz.

from sklearn.decomposition import PCA

# Criando o objeto PCA com 2 componentes
pca = PCA(n_components=2)

# Aplicando o PCA aos dados
pca.fit_transform(dados)

# Matriz com os valores das componentes
pca.components_.T

array([[ 0.04958152,  0.5667352 ],
       [-0.12158057, -0.4707658 ],
       [ 0.07439182, -0.13675161],
       [-0.29542205, -0.10814547],
       [-0.17454747,  0.20101716],
       [-0.09148996,  0.06782064],
       [ 0.60102901,  0.16135997],
       [-0.12722033, -0.09114733],
       [-0.5609105 ,  0.45015229],
       [ 0.09106457, -0.10145421],
       [ 0.06651806,  0.32394213],
       [-0.38256423, -0.17196911]])